# Generated by Django 5.2.7 on 2025-11-18 00:39

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0001_initial'),
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateTimeField(auto_now_add=True, verbose_name='Data Empréstimo')),
                ('data_devolucao', models.DateField(default=datetime.date.today, verbose_name='Data Devolução')),
                ('data_prevista_devolucao', models.DateField(default=datetime.date.today, verbose_name='Previsão devolução')),
                ('status', models.CharField(choices=[('E', 'Emprestado'), ('D', 'Devolvido')], max_length=1)),
                ('id_Aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.aluno', verbose_name='Aluno')),
                ('id_Livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livros.livro', verbose_name='Livro')),
            ],
        ),
    ]
