# Generated by Django 5.2.7 on 2025-11-18 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('edicao', models.CharField(max_length=2)),
                ('editora', models.CharField(max_length=50)),
                ('ano_publicacao', models.DateField()),
                ('isbn', models.CharField(max_length=14)),
                ('numero_paginas', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
                'db_table': 'Livro',
            },
        ),
    ]
